CREATE TABLE User (
	User_ID INT NOT NULL,
	First_Name VARCHAR(15) DEFAULT 'INFO',
	Last_Name VARCHAR(25) DEFAULT 'MISSING',
	Birthday DATE DEFAULT '1900-01-01',
	Funds DECIMAL(8) DEFAULT '0.00',
	Reward_Points INT DEFAULT '0',
	CONSTRAINT USEPK
	PRIMARY KEY (User_ID));

CREATE TABLE Seat (
	Seat_ID INT NOT NULL,
	Auditorium_ID INT NOT NULL,
	CONSTRAINT SEAPK
	PRIMARY KEY (Seat_ID));

CREATE TABLE Showtime (
	Showtime_ID INT NOT NULL,
	Time TIME NOT NULL,
	CONSTRAINT SHOWPK
	PRIMARY KEY (Showtime_ID));
    
CREATE TABLE Seat_Showtime (
	Seat_ID INT NOT NULL,
	Showtime_ID INT NOT NULL,
	User_ID INT,
	Constraint SESHPK
	PRIMARY KEY (Seat_ID,Showtime_ID),
	CONSTRAINT  SESHPK
	FOREIGN KEY (Seat_ID) REFERENCES SEAT(Seat_ID),
	CONSTRAINT SESHFPK
	FOREIGN KEY (Showtime_ID) REFERENCES SHOWTIME(Showtime_ID));

CREATE TABLE Auditorium (
	Auditorium_ID INT NOT NULL,
	Name VARCHAR(10) NOT NULL,
	Number_of_Seats INT NOT NULL,
	CONSTRAINT AUDPK
	PRIMARY KEY (Auditorium_ID));
    
CREATE TABLE Auditorium_Showtime (
	Showtime_ID INT NOT NULL,
	Auditorium_ID INT NOT NULL,
	CONSTRAINT AUDSHPK
	PRIMARY KEY (Showtime_ID,Auditorium_ID),
	CONSTRAINT AUDSHFPK
	FOREIGN KEY (Showtime_ID) REFERENCES SHOWTIME (Showtime_ID),
	CONSTRAINT AUDSHAFPK
	FOREIGN KEY (Auditorium_ID) REFERENCES AUDITORIUM (Auditorium_ID));
    
CREATE TABLE Film (
	Film_ID INT NOT NULL,
	Title VARCHAR(30) NOT NULL,
	Rating VARCHAR(5) NOT NULL,
	Runtime INT NOT NULL,
	CONSTRAINT FILMPK
	PRIMARY KEY (Film_ID));

CREATE TABLE Film_Showtime (
	Film_ID INT NOT NULL,
	Showtime_ID INT NOT NULL,
	CONSTRAINT FILSHPK
	PRIMARY KEY (Film_ID, Showtime_ID),
	CONSTRAINT FILSHSHFK
	FOREIGN KEY (Showtime_ID) REFERENCES SHOWTIME (Showtime_ID),
	CONSTRAINT FILSHFFK
	FOREIGN KEY (Film_ID) REFERENCES FILM (Film_ID));

